---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'bootstrap'
    - '$default'
  rewrite_hash_links: false
LectureHolderPage:
  extensions:
    - SilverStripe\Lumberjack\Model\Lumberjack
Sponsor:
  extensions:
    - SponsorExtension
SilverStripe\Assets\Image:
  belongs_many_many:
    Pages: Page.Images
SilverStripe\Assets\InterventionBackend:
  flush_enabled: false
SiteTree:
  extensions:
    - SilverStripe\StaticPublishQueue\Extension\Publishable\PublishableSiteTree